### ISSUE TITLE
Double inserting products

### ISSUE THREAD

**Issue by HarryMMR** [BennSandoval/Woodmin#1]
Hi, thanks for great sample. 
There is one issue in WoodminSyncAdapter.java. Sometimes, it will insert same product twice into database. 
I have changed the database Column_ID to be unique and set the database flag to something like this
long _id = db.insertWithOnConflict(WoodminContract.ProductEntry.TABLE_NAME,null,contentValues,SQLiteDatabase.CONFLICT_REPLACE);

But it still couldn't solve the problem. My guess is that there is probably a race condition in sync adapter. Any suggestion? Thanks.

**Comment by BennSandoval** [comment]
Awesome, Could you please confirm if that id is not duplicated on the Woocommerce API?

**Comment by HarryMMR** [comment]
I can confirm that API is correct. No duplication.
Double insertion occurs when race condition happens. You can try it out with your own API. Do a few runs and you will see.

For now, the issue seems to be solved after I added synchronized in methods like below.
 private synchronized void synchronizeProducts(final Woocommerce woocommerceApi, final Context context) { .. }

If you have a better fix, do let me know. Thanks Benn.

**Comment by BennSandoval** [comment]
Sure no problem, give me a week to take a look.

Thanks...
